import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./(dashboard)/notes/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Madros',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',

  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>

  );
}
